version: '3.8'
services:
  backend:
    build: ./backend2
    volumes:
      - ./backend2:/app
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development
    command: sh -c "python db_seed.py && flask run --host=0.0.0.0 --port=5050"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/challenges"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3 